### PR TITLE
pgrep: use rfind in stat split

### LINKED ISSUE #214: pgrep: incorrect parsing of `/proc/<pid>/stat` file
Parsing of stat file fails when the comm field contains a ' ' after the `)` or contains `$$`.

For example, the following test will fail:

```rust
let case = "83875 (sleep (2) .sh) S 75750 83875 75750 34824 83875 4194304 173 0 0 0 0 0 0 0 20 0 1 0 18366278 23187456 821 18446744073709551615 94424231874560 94424232638561 140734866834816 0 0 0 65536 4 65538 1 0 0 17 6 0 0 0 0 0 94424232876752 94424232924772 94424259932160 140734866837287 140734866837313 140734866837313 140734866841576 0";
assert!(stat_split(case)[1] == "sleep (2) .sh");
```

This causes pgrep to be unable to match these processes.

```
[xubiang@BIIIANGPC test]$ ./sleep\ \(2\)\ .sh &
[1] 3650
[xubiang@BIIIANGPC test]$ pgrep -l sleep
3650 sleep (2) .sh
3652 sleep
3711 sleep
[xubiang@BIIIANGPC test]$ ~/procps/target/debug/procps pgrep -l sleep
3652 sleep
3900 sleep
```

### PR DESCRIPTION
**Pull request by BIIIANG**
Fix #214

### CODE REVIEW

File: src/uu/pgrep/src/process.rs [hunk 1]
```diff
@@ -350,33 +350,21 @@ impl Hash for ProcessInformation {
...
 fn stat_split(stat: &str) -> Vec<String> {
     let stat = String::from(stat);
 
-    let mut buf = String::with_capacity(stat.len());
-
-    let l = stat.find('(');
-    let r = stat.find(')');
-    let content = if let (Some(l), Some(r)) = (l, r) {
-        let replaced = stat[(l + 1)..r].replace(' ', "$$");
+    if let (Some(l), Some(r)) = (stat.find('('), stat.rfind(')')) {
```
Comment (Krysztal112233) [inline src/uu/pgrep/src/process.rs:357]:
```suggestion
    if let (Some(left), Some(right)) = (stat.find('('), stat.rfind(')')) {
```

I think `left` instead of `l` would be better.

File: src/uu/pgrep/src/process.rs [hunk 2]
```diff
@@ -350,33 +350,21 @@ impl Hash for ProcessInformation {
...
+        let mut split_stat = vec![];
 
-        buf.push_str(&stat[..l]);
-        buf.push_str(&replaced);
-        buf.push_str(&stat[(r + 1)..stat.len()]);
+        split_stat.push(stat[..l - 1].to_string());
+        split_stat.push(stat[l + 1..r].to_string());
+        split_stat.extend(stat[r + 2..].split_whitespace().map(String::from));
```
Comment (Krysztal112233) [inline src/uu/pgrep/src/process.rs:362]:
```suggestion
        split_stat.push(stat[..left - 1].to_string());
        split_stat.push(stat[left + 1..right].to_string());
        split_stat.extend(stat[right + 2..].split_whitespace().map(String::from));
```

**Review by Krysztal112233 — CHANGES_REQUESTED** [review]
Look great, please go on :)

File: src/uu/pgrep/src/process.rs (hunk 1 above)
Comment (BIIIANG) [reply src/uu/pgrep/src/process.rs]: Modified :)

**Comment by Krysztal112233** [comment]
Great, thanks!
