### PR TITLE
ps: Fix the `time` code

### LINKED ISSUE #160: ps: Fix the `time` code
Except:

```shell
❯ ps
    PID TTY          TIME CMD
  16643 pts/1    00:00:03 zsh
  16660 pts/1    00:00:00 zsh
  16733 pts/1    00:00:00 zsh
  16734 pts/1    00:00:00 zsh
  16736 pts/1    00:00:00 gitstatusd-linu
 117274 pts/1    00:00:00 ps
```

But:

```shell
❯ cargo run ps
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.85s
     Running `target/debug/procps ps`
 PID     TTY    TIME      CMD 
 16643   pts/1  00:00:00  zsh 
 16660   pts/1  00:00:00  zsh 
 16733   pts/1  00:00:00  zsh 
 16734   pts/1  00:00:00  zsh 
 16736   pts/1  00:00:00  gitstatusd-linu 
 116825  pts/1  00:00:00  procps 
```

### PR DESCRIPTION
**Pull request by MCredbear**
fix #160

### CODE REVIEW

File: src/uu/ps/src/picker.rs [hunk 1]
```diff
@@ -54,13 +53,14 @@ fn time(proc_info: RefCell<ProcessInformation>) -> String {
...
 
-    DateTime::from_timestamp_millis(cumulative_cpu_time)
-        .unwrap()
-        .format("%H:%M:%S")
-        .to_string()
+    let hours = &cumulative_cpu_time / 3600;
+    let minutes = (&cumulative_cpu_time % 3600) / 60;
+    let seconds = &cumulative_cpu_time % 60;
+
+    format!("{:02}:{:02}:{:02}", hours, minutes, seconds)
```
Comment (Krysztal112233) [inline src/uu/ps/src/picker.rs:63]: Why use custom formatting here?

**Review by Krysztal112233 — CHANGES_REQUESTED** [review]
And if possible please add more tests, thanks for your contribution :)

**Comment by Krysztal112233** [comment]
And I noticed that the `[DD:]` might be optional in the outputs, I don't know the condition are :(

**Comment by MCredbear** [comment]
Expected:
```
redbear@localhost:~$ ps -A
    PID TTY          TIME CMD
      1 ?        00:00:10 systemd
      2 ?        00:00:00 kthreadd
      3 ?        00:00:00 pool_workqueue_release
      4 ?        00:00:00 kworker/R-rcu_g
      5 ?        00:00:00 kworker/R-slub_
      6 ?        00:00:00 kworker/R-netns
      9 ?        00:00:00 kworker/0:0H-events_highpri
     11 ?        00:00:00 kworker/R-mm_pe
     12 ?        00:00:00 rcu_tasks_kthread
     13 ?        00:00:00 rcu_tasks_trace_kthread
     14 ?        00:00:07 ksoftirqd/0
     15 ?        00:03:19 rcu_preempt
```
Now:
```
redbear@localhost:~/procps$ cargo run ps -A
   Compiling uu_ps v0.0.1 (/home/redbear/procps/src/uu/ps)
   Compiling procps v0.0.1 (/home/redbear/procps)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 2.35s
     Running `target/debug/procps ps -A`
 PID     TTY    TIME      CMD 
 1       ?      00:00:10  systemd 
 2       ?      00:00:00  kthreadd 
 3       ?      00:00:00  pool_workqueue_release 
 4       ?      00:00:00  kworker/R-rcu_g 
 5       ?      00:00:00  kworker/R-slub_ 
 6       ?      00:00:00  kworker/R-netns 
 9       ?      00:00:00  kworker/0:0H-events_highpri 
 11      ?      00:00:00  kworker/R-mm_pe 
 12      ?      00:00:00  rcu_tasks_kthread 
 13      ?      00:00:00  rcu_tasks_trace_kthread 
 14      ?      00:00:07  ksoftirqd/0 
 15      ?      00:03:19  rcu_preempt
```

File: src/uu/ps/src/picker.rs [hunk 2]
```diff
@@ -54,13 +53,19 @@ fn time(proc_info: RefCell<ProcessInformation>) -> String {
...
+    let days = cumulative_cpu_time / (3600 * 24);
+    let hours = (cumulative_cpu_time % (3600 * 24)) / 3600;
+    let minutes = (cumulative_cpu_time % 3600) / 60;
+    let seconds = cumulative_cpu_time % 60;
+
+    if days != 0 {
+        format!("{:02}-{:02}:{:02}:{:02}", days, hours, minutes, seconds)
+    } else {
+        format!("{:02}:{:02}:{:02}", hours, minutes, seconds)
+    }
```
Comment (Krysztal112233) [inline src/uu/ps/src/picker.rs:68]: I think you can move those to another function so that you can improve the testing coverage :P

File: src/uu/ps/src/picker.rs [hunk 3]
```diff
@@ -70,3 +75,47 @@ fn cmd(proc_info: RefCell<ProcessInformation>) -> String {
...
+
+        let result = if days != 0 {
+            format!("{:02}-{:02}:{:02}:{:02}", days, hours, minutes, seconds)
+        } else {
+            format!("{:02}:{:02}:{:02}", hours, minutes, seconds)
+        };
+
+        assert!(result == "132-12:57:07");
+    }
+}
```
Comment (Krysztal112233) [inline src/uu/ps/src/picker.rs:121]: As I said, you can coding your logic only once and make sure it's covered by unit tests XD.

**Review by Krysztal112233 — CHANGES_REQUESTED** [review]

File: src/uu/ps/src/picker.rs (hunk 1 above)
Comment (MCredbear) [reply src/uu/ps/src/picker.rs]: According to the manpage, the longest unit of `TIME` is day, if the time is longer than a month, `DateTime` will output wrongly.

File: src/uu/ps/src/picker.rs [hunk 4]
```diff
@@ -70,3 +80,22 @@ fn cmd(proc_info: RefCell<ProcessInformation>) -> String {
...
+
+#[test]
+fn test_time() {
+    assert!(
+        format_time({
+            let utime = 29i64;
+            let stime = 18439i64;
+            (utime + stime) / 100
+        }) == "00:03:04"
+    );
```
Comment (Krysztal112233) [inline src/uu/ps/src/picker.rs:92]:
```suggestion
    let formatted = {
        let time = {
            let utime = 29i64;
            let stime = 18439i64;
            (utime + stime) / 100
        };

        format_time(time)
    };
    assert_eq!(formatted, "00:03:04");
```

File: src/uu/ps/src/picker.rs [hunk 5]
```diff
@@ -70,3 +80,22 @@ fn cmd(proc_info: RefCell<ProcessInformation>) -> String {
...
+
+    assert!(
+        format_time({
+            let utime = 1145141919i64;
+            let stime = 810i64;
+            (utime + stime) / 100
+        }) == "132-12:57:07"
+    );
```
Comment (Krysztal112233) [inline src/uu/ps/src/picker.rs:100]: As same

File: src/uu/ps/src/picker.rs [hunk 6]
```diff
@@ -54,13 +53,24 @@ fn time(proc_info: RefCell<ProcessInformation>) -> String {
...
 
-    DateTime::from_timestamp_millis(cumulative_cpu_time)
-        .unwrap()
-        .format("%H:%M:%S")
-        .to_string()
+    format_time(cumulative_cpu_time)
+}
+
+// The unit is second
+fn format_time(time: i64) -> String {
```
Comment (Krysztal112233) [inline src/uu/ps/src/picker.rs:63]: Hum can you think out a name better than `time`?

**Review by Krysztal112233 — CHANGES_REQUESTED** [review]
There are some very minor glitches. Please fix them, thanks :)

**Comment by Krysztal112233** [comment]
I noticed that you commit a changed about `free` command, please make it as a new pull request.

Keep pull request as atomic as possible will helpful to project maintaince.

File: src/uu/ps/src/picker.rs [hunk 7]
```diff
@@ -54,13 +53,24 @@ fn time(proc_info: RefCell<ProcessInformation>) -> String {
...
+    let days = time / (3600 * 24);
+    let hours = (time % (3600 * 24)) / 3600;
+    let minutes = (time % 3600) / 60;
+    let seconds = time % 60;
```
[the remark this answers is not in the document]
Comment (MCredbear) [reply src/uu/ps/src/picker.rs:67]: As I metioned above, `let days = time.day();` will be wrong if the time is longer than a month.

[the remark this answers is not in the document]
Comment (Krysztal112233) [reply src/uu/ps/src/picker.rs:67]: Can you give me an example?

[the remark this answers is not in the document]
Comment (MCredbear) [reply src/uu/ps/src/picker.rs]:
```
    let time = 123456789000;
    let time = DateTime::from_timestamp(time, 0).unwrap();
    let days = time.day();
    println!("{}",days);
```
This is almost 1428898 days, but it prints 11.

**Review by Krysztal112233 — CHANGES_REQUESTED** [review]

File: src/uu/ps/src/picker.rs [hunk 8]
```diff
@@ -54,13 +53,23 @@ fn time(proc_info: RefCell<ProcessInformation>) -> String {
...
+}
+
+fn format_time(seconds: i64) -> String {
+    let day = seconds / (3600 * 24);
+    let hour = (seconds % (3600 * 24)) / 3600;
+    let minute = (seconds % 3600) / 60;
+    let second = seconds % 60;
+
+    if day != 0 {
+        format!("{:02}-{:02}:{:02}:{:02}", day, hour, minute, second)
```
[the remark this answers is not in the document]
Comment (MCredbear) [reply src/uu/ps/src/picker.rs:69]: I think it's code cov's bug, this 2 lines are already been covered.

[the remark this answers is not in the document]
Comment (Krysztal112233) [reply src/uu/ps/src/picker.rs:69]: Could you give me an example? I will tests on my machine.

[the remark this answers is not in the document]
Comment (MCredbear) [reply src/uu/ps/src/picker.rs:69]:
```
use std::cell::RefCell;

use uu_pgrep::process::{ProcessInformation, Teletype};

fn format_time(seconds: i64) -> String {
    let day = seconds / (3600 * 24);
    let hour = (seconds % (3600 * 24)) / 3600;
    let minute = (seconds % 3600) / 60;
    let second = seconds % 60;

    if day != 0 {
        format!("{:02}-{:02}:{:02}:{:02}", day, hour, minute, second)
    } else {
        format!("{:02}:{:02}:{:02}", hour, minute, second)
    }
}

#[test]
fn test_time() {
    let formatted = {
        let time = {
            let utime = 29i64;
            let stime = 18439i64;
            (utime + stime) / 100
        };
        format_time(time)
    };
    assert_eq!(formatted, "00:03:04");

    let formatted = {
        let time = {
            let utime = 12345678i64;
            let stime = 90i64;
            (utime + stime) / 100
        };
        format_time(time)
    };
    assert_eq!(formatted, "01-10:17:37");
}
```
Like this?

**Comment by cakebaker** [comment]
Thanks for your PR!
