### PR TITLE
pidof: Implemented `-o`

### LINKED ISSUE #119: pidof: support multiple PIDs with `-o`
The original `pidof` allows the user to specify multiple PIDs with `-o` whereas our `pidof` doesn't allow it.
```
$ pidof -o1282,5304 konsole
6531 6507 6482
$ cargo run pidof -o1282,5304 konsole
error: invalid value '1282,5304' for '-o <omitpid>': invalid digit found in string
```

### PR DESCRIPTION
**Pull request by Krysztal112233**
fix #119 

This commit implemented two usage of `-o` which are already implemented in GNU's implementation, but not in ours.

```shell
❯ cargo run pidof zsh
116473 116472 116401 116391

❯ cargo run pidof -o116473,116472 zsh
116401 116391

❯ cargo run pidof -o116473 -o116472 zsh
116401 116391
```

And the GNU's implementation:

```shell
❯ pidof zsh
116473 116472 116401 116391

❯ pidof -o116473,116472 zsh
116401 116391

❯ pidof -o116473 -o116472 zsh
116401 116391
```

### CODE REVIEW

File: tests/by-util/test_pidof.rs [hunk 1]
```diff
@@ -33,3 +33,29 @@ fn test_no_program() {
...
     new_ucmd!().arg("NO_THIS_PROGRAM").fails().code_is(1);
 }
+
+#[test]
+#[cfg(target_os = "linux")]
+fn test_quiet() {
+    let binding = new_ucmd!().arg("kthreadd").arg("-q").succeeds();
+    let output = binding.stdout();
+
+    assert!(output.is_empty())
```
Comment (cakebaker) [inline tests/by-util/test_pidof.rs:43]: You can simplify it to:
```suggestion
    new_ucmd!().arg("kthreadd").arg("-q").succeeds().no_output();
```

File: tests/by-util/test_pidof.rs [hunk 2]
```diff
@@ -33,3 +33,29 @@ fn test_no_program() {
...
+    let output = binding.stdout_str();
+
+    let binding = output.replace('\n', "");
+    let pids = binding.split(' ').collect::<Vec<_>>();
+    let first = pids[0];
+
+    let result = pids.iter().all(|it| *it == first);
+
+    assert!(result)
+}
```
Comment (cakebaker) [inline tests/by-util/test_pidof.rs:61]: I think this test is a better fit for #124 and so I would remove it from this PR. I already left two comments in #124.

File: src/uu/pidof/src/pidof.rs [hunk 3]
```diff
@@ -137,6 +137,7 @@ pub fn uu_app() -> Command {
             Arg::new("o")
                 .short('o')
                 .help("Omit results with a given PID")
+                .value_delimiter(',')
```
Comment (cakebaker) [inline src/uu/pidof/src/pidof.rs:140]: Nice, short and sweet :)

**Comment by cakebaker** [comment]
Thanks :)
